### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Xety** [teamreflex/DiscordPHP#174] opened 2016-11-08 20:39 UTC
Hello,

I was doing my bot when i did for fun a cmd to display the memory used by the script and... i noticed a huge memory leak.
I thought it was my script, but i tried with the exemple code and the memory leak is still there :

Code used to test it :
``` php
<?php
//Set the memory limit to 6MB else it will take forever to test it.
ini_set('memory_limit', '6M');

include __DIR__.'/vendor/autoload.php';

$discord = new \Discord\Discord([
    'token' => 'your-auth-token',
]);

$discord->on('ready', function ($discord) {
    echo "Bot is ready.", PHP_EOL;

    // Listen for events here
    $discord->on('message', function ($message) {

        $memoryKo = round(memory_get_usage() / 1024);
        $memoryMo = number_format($memoryKo / 1024, 1, ',', ' ');

        $message->channel->sendMessage('Memory used : `' . $memoryKo . 'Ko` (`' . $memoryMo . 'Mo`).');


        echo "Recieved a message from {$message->author->username}: {$message->content}", PHP_EOL;
    });
});

$discord->run();
```

Write a message in a channel and you will see the memory leak. 

![887ae1350b3dfea1b218f64ae2e0601e1](https://cloud.githubusercontent.com/assets/8210023/20115999/ce5ef838-a5fa-11e6-9b1c-8cdc3aeadb07.png)

I don't know if this memory leak come from this library or from another one.

**Comment by sciencefyll** [comment] 2017-01-03 02:24
I've noticed this as well. We made a "hack fix" by restarting the bot every now and then, otherwise everything would crash 0.o

**Comment by sciencefyll** [comment] 2017-01-03 03:22
Might be: DiscordPHP/src/Discord/Discord.php $logger.

@aequasi @Sleavely @xKairu @danielholmes

**Comment by Sleavely** [comment] 2017-01-03 10:07
Is the bot connected to voice chat? In that case it might be what @sciencefyll mentioned, the [voice logger being initiated](https://github.com/teamreflex/DiscordPHP/blob/b44c4be11281827ec493c80d1a319eca3f46d849/src/Discord/Discord.php#L1060) over and over.

I think, however, it has to do with the [repositories](https://github.com/teamreflex/DiscordPHP/tree/b44c4be11281827ec493c80d1a319eca3f46d849/src/Discord/Repository) where everything is stored in memory. It seems that messages are stored in an array there, and are [duplicated(?)](https://github.com/teamreflex/DiscordPHP/blob/b44c4be11281827ec493c80d1a319eca3f46d849/src/Discord/WebSockets/Events/MessageUpdate.php#L43) when an update occurs to a message. That being said, I'm not really a contributor to this project nor have a working Discord bot I can test this against.

**Comment by davidcole1340** [comment] 2020-08-11 00:28
Memory leak is a known problem, thank you for locating some potential areas for this leak. Going to have a look at it after going through the rest of the issues.

**Comment by Xety** [comment] 2020-08-16 15:33
Hey,
I saw that you're reviving this project, that's a great new !
I used your project to build a framework to create bot https://github.com/SkinnyBot/Skinny and also to build a bot for a big community but sadly i had to switch to https://github.com/theteamcoders/Yasmin which was abandonned too.
I have to rewrite my bot so i hope you will continue to revive this project which is actually the only one in PHP.

**Comment by davidcole1340** [comment] 2020-08-31 14:17
Closing. Can't seem to see any issues with memory at the moment.

**Comment by xxAROX** [comment] 2020-09-15 19:54
The bot triggers himself, cancel it:
```php
		if ($message->author->id == $discord->id) {
			return;
		}
```

**Comment by davidcole1340** [comment] 2020-10-11 01:39
Again seems to have gone and I cannot reproduce, closing.

**Closed by davidcole1340** 2020-10-11 01:39 UTC
Labels: bug
