### ISSUE TITLE
createRole

### ISSUE THREAD

**Issue by ghost** [teamreflex/DiscordPHP#172] opened 2016-11-03 12:42 UTC
It seems that without github issue nothing changing here, so here we go:
Code: 
>    $guild->createRole($opts) ->then(
                        function ($role) {
                            $this->log('updateUser', 'Create role ok. (' . $role->name . ')');
                        },
                        function (\Exception $e) {
                            $this->log('updateUser', 'Create role not ok. ' . $e->getMessage());
                        }
                    );

Error:
> Create role not ok. An error occurred in the underlying stream

On dev-develop it will create some roles, some - dont. Also creating duplicate roles. Overall - working strange.

**Comment by uniquoooo** [comment] 2016-11-03 22:09
Can you update your project with `composer update`?

**Comment by Caravus** [comment] 2016-11-03 22:22
composer.json:
>     "team-reflex/discord-php": "dev-develop",

composer update:
> Nothing to install or update

composer show | grep react/http-client
> react/http-client                    v0.4.14             Asynchronous HTTP client library.

**Comment by Caravus** [comment] 2016-11-09 10:11
Any news?

**Comment by uniquoooo** [comment] 2016-11-11 20:54
I'll try reproduce this a bit later today.

**Comment by uniquoooo** [comment] 2016-11-12 08:47
Works fine for me, are you sure you are on the latest version?

**Comment by Caravus** [comment] 2016-11-13 18:35
updated now just before test:           
>Removing react/stream (v0.4.4) 
>Installing react/stream (v0.4.5)
>Updating team-reflex/discord-php dev-develop (1651097 => 8f6d568)

Test: http://pastebin.com/pkJkcHR7
Result:
> Create role ERROR (role_14) Connection closed before receiving response
> Create role ERROR (role_29) Connection closed before receiving response
> Create role ERROR (role_20) Connection closed before receiving response
> Create role ERROR (role_30) Connection closed before receiving response
> Create role ERROR (role_26) Connection closed before receiving response
> Create role ERROR (role_16) Connection closed before receiving response
> Create role ERROR (role_51) Connection closed before receiving response
> ...
Some roles ok, some - "new role".

**Comment by davidcole1340** [comment] 2020-08-11 00:20
You may be getting ratelimited. Closing due to age.

**Closed by davidcole1340** 2020-08-11 00:20 UTC
