### ISSUE TITLE
sendFile not working

### ISSUE THREAD

**Issue by gsfordham** [teamreflex/DiscordPHP#182] opened 2016-11-21 18:14 UTC
```php
$message->channel->sendFile( __DIR__ . "/media/test.jpg", "test.jpg", "testContent");
```
So, the file won't let me rename it after running this. Says the file is OPEN with PHP, but the thing is: it doesn't send. When the file doesn't even exist, it sends an empty, 0kb file of name "test.jpg" and echos an error to my prompt, but when the file exists, it does nothing. At all. It doesn't write an error to my prompt, but it also doesn't send the file; it's as if it succeeded in sending it, but it didn't.
And it STILL responds afterward, so it's not hanging. It just opens the file, does nothing with it, and then continues.

Is there a different way I'm supposed to do this?

**Comment by darklandz** [comment] 2016-11-21 18:29
I have the same problem

`if ($message->content == $config["bot"]["trigger"].'test')
                {
                    $message->channel->sendFile( __DIR__ . "/asgard.jpg", "asgard.jpg", "testContent");
                }`

nothing happens and even i get no error message

**Comment by gsfordham** [comment] 2016-12-06 22:14
Still no updates to this?

**Comment by uniquoooo** [comment] 2016-12-09 01:10
@gsfordham @darklandz Sorry for late reply, not sure about `master` but `sendFile` is working on the `develop` branch. I'll push a release to master sometime today.

**Comment by illu23** [comment] 2016-12-13 21:13
got the same problem and no error output .. got in the runRequest from httpdriver but my php coding experience is not that good :/

**Comment by haolink** [comment] 2017-01-08 10:43
I can confirm this isn't working.

I was trying both on version v4.* in composer.json as well as dev-develop. On v4.* the entire php process is crashing, on dev-develop it seems to be trying to send a file but it fails to submit the Promise.

```
#0 [internal function]: React\HttpClient\Request->handleError(Object(RuntimeException), Object(React\Stream\Stream))
#1 /srv/dphp/bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Array, Array)
#2 /srv/dphp/bot/vendor/react/stream/src/Stream.php(61): Evenement\EventEmitter->emit('error', Array)
#3 [internal function]: React\Stream\Stream->React\Stream\{closure}(Object(RuntimeException), Object(React\Stream\Buffer))
#4 /srv/dphp/bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Object(Closure), Array)
#5 /srv/dphp/bot/vendor/react/stream/src/Buffer.php(110): Evenement\EventEmitter->emit('error', Array)
#6 [internal function]: React\Stream\Buffer->handleWrite(Resource id #245, Object(React\EventLoop\StreamSelectLoop))
#7 /srv/dphp/bot/vendor/react/event-loop/src/StreamSelectLoop.php(240): call_user_func(Array, Resource id #245, Object(React\EventLoop\StreamSelectLoop))
#8 /srv/dphp/bot/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(34387433.052063)
#9 /srv/dphp/bot/vendor/team-reflex/discord-php/src/Discord/Discord.php(1231): React\EventLoop\StreamSelectLoop->run()
#10 /srv/dphp/bot/test.php(54): Discord\Discord->run()
```

The code is kept rather simple because I wasn't sure if my big project was broken. So I literally broke it down to:

```php
$discord = new Discord([
    'token' => $token
]);

$discord->on('ready', function ($discord) {
    echo "Bot is ready!", PHP_EOL;

    // Listen for messages.
    $discord->on('message', function ($message, $discord) {
        $message->channel->sendFile('/srv/dphp/files/img_10F4b1C7ffQrPeo.jpg', 'img.jpg', 'Image', false)
                ->then(
                        function($msg) {
                                echo 'OKAY!';
                                die('Bye bye'); //Making sure it won't reply to itself!
                        })
                ->otherwise(
                        function($e) {
                                echo $e->getMessage() . PHP_EOL;
                                echo $e->getTraceAsString() . PHP_EOL;
                        });
    });
});

$discord->run();
```

**Comment by haolink** [comment] 2017-01-09 19:38
Okay, I shall reply myself here - this is something interesting.

I was debugging into the error - and well, DiscordPHP is not to blame. This seems to be an error which only occurs on certain PHP configurations. I'm using Ubuntu 16.04 with Ondrej Sury's PHP PPA (see https://launchpad.net/~ondrej/+archive/ubuntu/php ).

Personally I am thus using PHP 7.0.14 to run the bot.

The bug affects the OpenSSL extension of PHP - I can reconstruct it in PHP 5.6, PHP 7.0 and PHP 7.1 - I created a separate PHP CLI client by recompiling Ondrej Sury's PHP CLI interpreter with the bug fix at PHP from https://bugs.php.net/bug.php?id=72333 included (not as /usr/bin/php but as /usr/bin/php_sslbot so that a future package upgrade wouldn't immediately overwrite it).

The bug is also discussed at the ReactPHP GitHub see https://github.com/reactphp/stream/issues/64 - so yeah, so far using this recompiled PHP works - I doubt this is a bug DiscordPHP can fix for affected PHP installations.

**Comment by Shadowfied** [comment] 2017-01-21 10:22
For me, files under 100 KB work.
My php.ini allows for several MBs (upload_max_filesize, post_max_size etc)..
Any ideas?

**Comment by BuzzMoody** [comment] 2017-02-17 06:35
Yeah this still doesn't work, looks like PHP peeps aren't in a rush to fix it.

**Comment by aequasi** [comment] 2017-02-17 06:37
@BuzzMoody "@ gsfordham @ darklandz Sorry for late reply, not sure about master but sendFile is working on the develop branch. I'll push a release to master sometime today. Is there another issue that I don't see?"

**Comment by BuzzMoody** [comment] 2017-02-17 06:48
Doesn't work on either branch on both Debian and Ubuntu.

**Comment by BuzzMoody** [comment] 2017-02-19 09:52
@haolink Able to share your recompiled PHP CLI client?

**Comment by donkkill13** [comment] 2017-02-19 09:55
I'm pretty sure that replacing fopen() with file_get_contents() will fix the issue, but it won't be as clean and I think file_get_contents() blocks or something

**Comment by haolink** [comment] 2017-03-16 17:14
The issue is finally fixed on the PHP upstream. See http://git.php.net/?p=php-src.git;a=commit;h=17e9fc9bfeaf575b25782a42937a56e809155858

@BuzzMoody - sorry I didn't notice your ping so I didn't react. The thing is: I can share the client but it's basically built from Ondrej Sury's PHP 7.0 builds - so it is linked against Ubuntu 16.04 and PHP 7.0 libraries by him - I tested on Vanilla Ubuntu 16.04 and like expected it didn't run - it ran into many missing libraries. So yeah: if you have such a configuration I can share the binary - if not it will probably be a waste of time - however, the upstream of PHP has it, so if you use quick release cycles you should have it rather soon ^^.

**Comment by davidcole1340** [comment] 2020-08-11 00:51
Closing as this seems to be fixed with PHP. Working for me on develop branch.

**Comment by BuzzMoody** [comment] 2020-10-04 05:09
Still not working on Debian 10, PHP 7.4.10 and dev branch

**Comment by Ravisdo** [comment] 2020-10-04 05:13
@BuzzMoody could you retry with the latest master? It got a few changes in the last past days

**Comment by BuzzMoody** [comment] 2020-10-04 05:52
> @BuzzMoody could you retry with the latest master? It got a few changes in the last past days

"PHP Warning:  array_key_exists() expects parameter 2 to be array, bool given in /home/buzz/DiscordPHP/vendor/team-reflex/discord-php/src/Discord/Http/Http.php on line 145"

**Comment by davidcole1340** [comment] 2020-10-04 09:26
Line 145 on the `master` branch is an anonymous function line, it's likely you are on an older version. Can you run `composer require team-reflex/discord-php dev-master` to get the latest.

**Comment by BuzzMoody** [comment] 2020-10-04 10:29
Hey David, I updated to dev-master as you suggested. I now no longer get any errors it just won't send the image. No output, but keeps running fine.

**Comment by davidcole1340** [comment] 2020-10-04 10:40
@BuzzMoody Could you update again please, just with `composer update`. It's working for me now, seemed to be an oversight when switching to `react/http` however we only made the switch a couple weeks ago so there could be another issue for you.

**Comment by BuzzMoody** [comment] 2020-10-04 10:46
It's working! You're a genius <3

**Closed** 2020-10-04 13:28 UTC
