### ISSUE TITLE
Websocket error (op 0)

### ISSUE THREAD

**Issue by NobDod** [teamreflex/DiscordPHP#284] opened 2019-08-31 16:54 UTC
Hi, when I run the bot, gives an error `discordPHP.WARNING: websocket closed {"op":0,"reason":"websocket error"} []`

I use php 5.6, Windows 10.
How to fix?

**Comment by Adrriii** [comment] 2019-09-07 12:17
I am also getting this error on Debian 10

**Comment by NobDod** [comment] 2019-09-07 14:01
No one wants to upgrade, most likely DiscordPHP died...

**Comment by Adrriii** [comment] 2019-09-07 14:07
Yup, time to rewrite code. Can't be too bad on the long run anyway

**Comment by garrettw** [comment] 2019-09-10 17:46
> No one wants to upgrade, most likely DiscordPHP died...

The [README](https://github.com/teamreflex/DiscordPHP) clearly says this.

**Comment by Adrriii** [comment] 2019-09-10 19:26
I might be interested in this, thanks you !

**Comment by davidcole1340** [comment] 2020-08-11 02:37
Closing due to age. If this error is still happening please create a new issue with steps to reproduce. I have no issues.

**Closed by davidcole1340** 2020-08-11 02:37 UTC
